# Motor control abstractions (placeholder)
class MotorController:
    def __init__(self, cfg):
        self.cfg = cfg
    def enable(self): ...
    def disable(self): ...
    def set_speed(self, rpm: float): ...
