# Sensor interfaces (placeholder)
class Sensors:
    def __init__(self, cfg):
        self.cfg = cfg
    def read_low_primer(self) -> bool: ...
    def read_powder_check(self) -> bool: ...
    def read_encoder(self) -> float: ...
